source_directories:
    - /mnt/source/vmail
    - /mnt/source/crypt
    - /mnt/source/redis
    - /mnt/source/rspamd
    - /mnt/source/postfix
repositories:
    - path: ssh://u******@u******.your-storagebox.de:23/./backups
      label: hetzner
exclude_patterns:
    - '/mnt/source/postfix/public/'
    - '/mnt/source/postfix/private/'
    - '/mnt/source/rspamd/rspamd.sock'

keep_hourly: 24
keep_daily: 7
keep_weekly: 4
keep_monthly: 6

ssh_command: ssh -i /root/.ssh/<keyfile>

mysql_databases:
    - name: mailcow
      username: <user>
      password: <pass>
      options: --default-character-set=utf8mb4
